version: "3"
services:
  notebook:
    build:
      context: .
    container_name: jupyter
    image: jupyter-notebook:latest
    volumes:
      - .:/app
    ports:
      - 8888:8888
    command: jupyter notebook --allow-root --NotebookApp.ip 0.0.0.0